on:
  pull_request:
  push:

name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishUrl: https://primarybranch.dev2.semgrep.dev
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
